version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "JST"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: "increase"