version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: "increase"