version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:50"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: "increase"
